### ISSUE TITLE
Awesome API --> Feature request: Spanish translation of QUOTES

### ISSUE THREAD

**Issue by inglesuniversal** [fisenkodv/dictum#119]
Is it possible to have /es/ --> spanish as an option for the included QUOTES?

That would make your API twice as valuable as it is today.

Best regards

Hugo Barbosa
Co-Founder INGLÉS UNIVERSAL® 
inglesuniversal.com

**Comment by fisenkodv** [comment]
@inglesuniversal the current implementation will work with `es`, please refer to https://github.com/fisenkodv/dictum/blob/895e4dd495d9a27903842ef38199c7cb3fc871b5/dictum-service/src/main/java/net/fisenko/dictum/micronaut/controller/QuotesController.java#L25

the `language` parameter is part of route. If in the database would `es` quotes and authors, the service should return them automatically without any code changes.

Unfortunately, at this moment I didn't have quotes in spanish. I would love to add spanish quotes and authors.
