### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by imuhammadosama** [fisenkodv/dictum#205]
Access to XMLHttpRequest at 'https://api.fisenko.net/v1/quotes/en/random' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by fisenkodv** [comment]
@imuhammadosama the following code
```ts
const response = await fetch('https://api.fisenko.net/v1/quotes/en/random');
const quote = await response.json();
setQuote(JSON.stringify(quote, null, 2)); // sets React state to show on the UI
```
works as expected with no errors, see the screenshot below

![PeeMtc7j_01052023@2x](https://user-images.githubusercontent.com/1039447/210806688-2cc1543c-be58-4d97-8019-62569a7e87bc.png)

**Comment by fisenkodv** [comment]
Please reopen if you see see it again.
